export const SET_CAMPUS = 'SET_CAMPUS'

export const SET_CURRENT_CAMPUS = 'SET_CURRENT_CAMPUS'

export const SET_BUILDINGS = 'SET_BUILDINGS'

export const SET_CURRENT_BUILDING = 'SET_CURRENT_BUILDING'

export const SET_BUILDING_TYPES = 'SET_BUILDING_TYPES'

export const SET_CURRENT_BUILDING_TYPE = 'SET_CURRENT_BUILDING_TYPE'

export const SET_AGENCIES = 'SET_AGENCIES'

export const SET_CURRENT_AGENCY = 'SET_CURRENT_AGENCY'

export const SET_AGENCY_TYPES = 'SET_AGENCY_TYPES'

export const SET_CURRENT_AGENCY_TYPE = 'SET_CURRENT_AGENCY_TYPE'

export const SET_INFORMATIONS = 'SET_INFORMATIONS'

export const SET_CURRENT_INFORMATION = 'SET_CURRENT_INFORMATION'

export const SET_INFORMATION_TYPES = 'SET_INFORMATION_TYPES'

export const SET_CURRENT_INFORMATION_TYPE = 'SET_CURRENT_INFORMATION_TYPE'

export const SET_PARTIES = 'SET_PARTIES'

export const SET_CURRENT_PARTY = 'SET_CURRENT_PARTY'

export const SET_SEARCH_PARAMS = 'SET_SEARCH_PARAMS'

export const SET_MAP_ZOOM = 'SET_MAP_ZOOM'

export const SET_BUILDING_IMG_LIST = 'SET_BUILDING_IMG_LIST'

export const SET_START_POS = 'SET_START_POS'

export const SET_END_POS = 'SET_END_POS'

export const SET_GUIDES = 'SET_GUIDES'

export const SET_TIPS = 'SET_TIPS'

export const SET_CURRENT_TIP = 'SET_CURRENT_TIP'

export const SET_LEADS = 'SET_LEADS'

export const SET_CURRENT_LEAD = 'SET_CURRENT_LEAD'

export const SET_CURRENT_GUIDE = 'SET_CURRENT_GUIDE'

export const SET_LOCATION_TYPE = 'SET_LOCATION_TYPE'

export const SET_TRANSIT_TYPE = 'SET_TRANSIT_TYPE'

export const SET_WAY_FLAG = 'SET_WAY_FLAG'


