const state = {
  campus : [],
  currentCampus : null,
  buildings : [],
  currentBuilding : null,
  buildingTypes : [],
  currentBuildingType : null,
  agencies : [],
  currentAgency : null,
  agencyTypes : [],
  currentAgencyType : null,
  informations : [],
  currentInformation : null,
  informationTypes : [],
  currentInformationType : null,
  parties : [],
  currentParty : null,
  searchParams : '',
  mapZoom : 17,
  buildingImgList : [],
  startPos : null,
  endPos : null,
  guides : [],
  tips : [],
  currentTip : null,
  leads : [],
  currentLead : null,
  currentGuide : null,
  locationType : 0,
  transitType : 0,
  wayFlag : false
}

export default state